/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d525f5a7b158e50f28eb4af
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import DialogDelete from "../components/DialogDelete";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import Button from "@material-ui/core/Button";
// import Table from "@material-ui/core/Table";
// import TableBody from "@material-ui/core/TableBody";
// import TableCell from "@material-ui/core/TableCell";
// import TableHead from "@material-ui/core/TableHead";
// import TableRow from "@material-ui/core/TableRow";

// Table
import EnhancedTable from "../components/EnhancedTable";

// Custom Actions


// START IMPORT ACTIONS
import BookingActions from "../redux/actions/BookingActions";

// END IMPORT ACTIONS

/** APIs

* actionsBooking.delete
*	@description CRUD ACTION delete
*	@param ObjectId id - Id
*
* actionsBooking.list
*	@description CRUD ACTION list
*

**/


class BookingList extends Component {
  // Init component
  constructor(props) {
    super(props);
    this.state = {
      openDialogDelete: false
    };
  }

  // Load data on start
  componentWillMount() {
    this.props.actionsBooking.loadBookingList();
  }

  // Delete data
  delete(id) {
    this.setState({ openDialogDelete: true, idDelete: id });
  }

  closeDialogDelete() {
    this.setState({ openDialogDelete: false, idDelete: null });
  }

  confirmDialogDelete(id) {
    this.props.actionsBooking.deleteBooking(this.state.idDelete).then(data => {
      this.props.actionsBooking.loadBookingList();
      this.setState({ openDialogDelete: false, idDelete: null });
    });
  }

  // Show content
  render() {
    const columns = [ 
      {
        id: "CarID",
        type: "string",
        label: "CarID"
      }, 
      {
        id: "DriverID",
        type: "string",
        label: "DriverID"
      }, 
      {
        id: "EndPlaceLat",
        type: "number",
        label: "EndPlaceLat"
      }, 
      {
        id: "EndPlaceLng",
        type: "number",
        label: "EndPlaceLng"
      }, 
      {
        id: "EndTime",
        type: "date",
        label: "EndTime"
      }, 
      {
        id: "StartPlaceLat",
        type: "number",
        label: "StartPlaceLat"
      }, 
      {
        id: "StartPlaceLng",
        type: "number",
        label: "StartPlaceLng"
      }, 
      {
        id: "StartTime",
        type: "date",
        label: "StartTime"
      }, 
      {
        id: "Status",
        type: "integer",
        label: "Status"
      },
    ];
    const link = "/bookings/";

    return (
      <div>
        <h1>Booking List</h1>

        <EnhancedTable
          data={this.props.list}
          columns={columns}
          link={link}
          onDelete={this.delete.bind(this)}
        />

        <DialogDelete
          open={this.state.openDialogDelete}
          onClose={this.closeDialogDelete.bind(this)}
          onConfirm={this.confirmDialogDelete.bind(this)}
        />

        {/*
        <Table>
          <TableHead>
            <TableRow>
              <TableCell>ID</TableCell>
              <TableCell align="right">CarID</TableCell>
              <TableCell align="right">DriverID</TableCell>
              <TableCell align="right">EndPlaceLat</TableCell>
              <TableCell align="right">EndPlaceLng</TableCell>
              <TableCell align="right">EndTime</TableCell>
              <TableCell align="right">StartPlaceLat</TableCell>
              <TableCell align="right">StartPlaceLng</TableCell>
              <TableCell align="right">StartTime</TableCell>
              <TableCell align="right">Status</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {this.props.list.map(row => (
              <TableRow key={row._id}>
                <TableCell component="th" scope="row">
                  <Link to={"/bookings/" + row._id} key={row._id}>
                    {row._id}
                  </Link>
                </TableCell>
                <TableCell align="right">{ row.CarID }</TableCell>
                <TableCell align="right">{ row.DriverID }</TableCell>
                <TableCell align="right">{ row.EndPlaceLat }</TableCell>
                <TableCell align="right">{ row.EndPlaceLng }</TableCell>
                <TableCell align="right">{ row.EndTime }</TableCell>
                <TableCell align="right">{ row.StartPlaceLat }</TableCell>
                <TableCell align="right">{ row.StartPlaceLng }</TableCell>
                <TableCell align="right">{ row.StartTime }</TableCell>
                <TableCell align="right">{ row.Status }</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
        */}

        <div className="footer-card">
          <Link to="/bookings/new">
            <Button variant="contained" color="primary">
              Add
            </Button>
          </Link>
        </div>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsBooking: bindActionCreators(BookingActions, dispatch),
  };
};

// Validate types
BookingList.propTypes = { 
  actionsBooking: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    list: state.BookingListReducer.listBooking
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(BookingList);
