/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d525f5a7b158e50f28eb4af
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import { DateTimePicker } from "material-ui-pickers";
import Select from "@material-ui/core/Select";
import MenuItem from "@material-ui/core/MenuItem";
import InputLabel from "@material-ui/core/InputLabel";
import FormControl from "@material-ui/core/FormControl";

// Custom Actions


// START IMPORT ACTIONS
import BookingActions from "../redux/actions/BookingActions";

// END IMPORT ACTIONS

/** APIs

* actionsBooking.create
*	@description CRUD ACTION create
*
* actionsBooking.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsBooking.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*

**/

class BookingEdit extends Component {
  // Init booking
  constructor(props) {
    super(props);
    this.state = {
      booking: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsBooking.loadBooking(this.props.match.params.id);
    }
    
  }

  // Insert props booking in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      booking: props.booking
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.booking._id) {
      this.props.actionsBooking.saveBooking(this.state.booking).then(data => {
        this.props.history.push("/bookings/");
      });
    } else {
      this.props.actionsBooking.createBooking(this.state.booking).then(data => {
        this.props.history.push("/bookings/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Booking Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="CarID"
            label="CarID"
            value={this.state.booking.CarID || ""}
            onChange={Utils.handleChange.bind(this, "booking")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="DriverID"
            label="DriverID"
            value={this.state.booking.DriverID || ""}
            onChange={Utils.handleChange.bind(this, "booking")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="EndPlaceLat"
            label="EndPlaceLat"
            value={this.state.booking.EndPlaceLat || ""}
            onChange={Utils.handleChange.bind(this, "booking")}
            type="number"
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="EndPlaceLng"
            label="EndPlaceLng"
            value={this.state.booking.EndPlaceLng || ""}
            onChange={Utils.handleChange.bind(this, "booking")}
            type="number"
            margin="normal"
            fullWidth
          />
          
          <DateTimePicker
            id="EndTime"
            label="EndTime"
            className="mt-20 mb-20"
            ampm={false}
            value={
              this.state.booking.EndTime
                ? new Date(this.state.booking.EndTime)
                : null
            }
            onChange={Utils.handleChangeDate.bind(this, "booking", "EndTime")}
            fullWidth
            autoOk
            disableFuture
          />
          
          
          <TextField
            id="StartPlaceLat"
            label="StartPlaceLat"
            value={this.state.booking.StartPlaceLat || ""}
            onChange={Utils.handleChange.bind(this, "booking")}
            type="number"
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="StartPlaceLng"
            label="StartPlaceLng"
            value={this.state.booking.StartPlaceLng || ""}
            onChange={Utils.handleChange.bind(this, "booking")}
            type="number"
            margin="normal"
            fullWidth
          />
          
          <DateTimePicker
            id="StartTime"
            label="StartTime"
            className="mt-20 mb-20"
            ampm={false}
            value={
              this.state.booking.StartTime
                ? new Date(this.state.booking.StartTime)
                : null
            }
            onChange={Utils.handleChangeDate.bind(this, "booking", "StartTime")}
            fullWidth
            autoOk
            disableFuture
          />
          
          <FormControl fullWidth required
              {...(!this.state.booking.Status && !this.state.booking.Status
                ? { error: true }
                : {})}>
            <InputLabel shrink htmlFor="Status">
              Status
            </InputLabel>
            <Select
              value={this.state.booking.Status || ""}
              onChange={Utils.handleChangeSelect.bind(this, "booking")}
              inputProps={{
                id: "Status",
                name: "Status"
              }}
              fullWidth
            >
              <MenuItem value="">
                <em>None</em>
              </MenuItem>
              <MenuItem value={"Canceled"}>Canceled</MenuItem>
              <MenuItem value={"Finished"}>Finished</MenuItem>
              <MenuItem value={"Moving"}>Moving</MenuItem>
              <MenuItem value={"Paused"}>Paused</MenuItem>
            </Select>
          </FormControl>

          {/* Footer */}
          <div className="footer-card">
            <Link to="/bookings/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsBooking: bindActionCreators(BookingActions, dispatch),
  };
};

// Validate types
BookingEdit.propTypes = { 
  actionsBooking: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    booking: state.BookingEditReducer.booking
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(BookingEdit);
