/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d525f5a7b158e50f28eb4af
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import Select from "@material-ui/core/Select";
import MenuItem from "@material-ui/core/MenuItem";
import InputLabel from "@material-ui/core/InputLabel";
import FormControl from "@material-ui/core/FormControl";

// Custom Actions


// START IMPORT ACTIONS
import TrackActions from "../redux/actions/TrackActions";

// END IMPORT ACTIONS

/** APIs

* actionsTrack.create
*	@description CRUD ACTION create
*
* actionsTrack.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsTrack.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*

**/

class TrackEdit extends Component {
  // Init track
  constructor(props) {
    super(props);
    this.state = {
      track: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsTrack.loadTrack(this.props.match.params.id);
    }
    
  }

  // Insert props track in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      track: props.track
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.track._id) {
      this.props.actionsTrack.saveTrack(this.state.track).then(data => {
        this.props.history.push("/tracks/");
      });
    } else {
      this.props.actionsTrack.createTrack(this.state.track).then(data => {
        this.props.history.push("/tracks/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Track Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="BookID"
            label="BookID"
            value={this.state.track.BookID || ""}
            onChange={Utils.handleChange.bind(this, "track")}
            margin="normal"
            fullWidth
            required
            {...(!this.state.track.BookID && this.state.track.BookID === ""
              ? { error: true }
              : {})}
          />
          
          <FormControl fullWidth required
              {...(!this.state.track.Status && !this.state.track.Status
                ? { error: true }
                : {})}>
            <InputLabel shrink htmlFor="Status">
              Status
            </InputLabel>
            <Select
              value={this.state.track.Status || ""}
              onChange={Utils.handleChangeSelect.bind(this, "track")}
              inputProps={{
                id: "Status",
                name: "Status"
              }}
              fullWidth
            >
              <MenuItem value="">
                <em>None</em>
              </MenuItem>
              <MenuItem value={"Canceled"}>Canceled</MenuItem>
              <MenuItem value={"Finished"}>Finished</MenuItem>
              <MenuItem value={"Moving"}>Moving</MenuItem>
            </Select>
          </FormControl>

          {/* Footer */}
          <div className="footer-card">
            <Link to="/tracks/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsTrack: bindActionCreators(TrackActions, dispatch),
  };
};

// Validate types
TrackEdit.propTypes = { 
  actionsTrack: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    track: state.TrackEditReducer.track
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(TrackEdit);
